import type { FactorKey } from './countries'

export type FactorOverrides = Record<string, Partial<Record<FactorKey, number>>>

// Generated by ingestion/update-indicators.mjs on 2026-03-07
export const indicatorOverridesGeneratedAt = '2026-03-07'

export const liveFactorConfidence: Partial<Record<FactorKey, number>> = {
  economicStrength: 0.82,
  taxTariffFriction: 0.8,
}

export const indicatorFactorOverrides: FactorOverrides = {
  "US": {
    "economicStrength": 41,
    "taxTariffFriction": 48
  },
  "DE": {
    "economicStrength": 35,
    "taxTariffFriction": 38
  },
  "SG": {
    "economicStrength": 86,
    "taxTariffFriction": 0
  },
  "CA": {
    "economicStrength": 33,
    "taxTariffFriction": 39
  },
  "AE": {
    "economicStrength": 49,
    "taxTariffFriction": 34
  },
  "GB": {
    "economicStrength": 34,
    "taxTariffFriction": 36
  },
  "FR": {
    "economicStrength": 42,
    "taxTariffFriction": 39
  },
  "NL": {
    "economicStrength": 41,
    "taxTariffFriction": 29
  },
  "JP": {
    "economicStrength": 37,
    "taxTariffFriction": 42
  },
  "AU": {
    "economicStrength": 33,
    "taxTariffFriction": 42
  },
  "IN": {
    "economicStrength": 54,
    "taxTariffFriction": 82
  },
  "BR": {
    "economicStrength": 46,
    "taxTariffFriction": 99
  },
  "MX": {
    "economicStrength": 37,
    "taxTariffFriction": 42
  },
  "ES": {
    "economicStrength": 48,
    "taxTariffFriction": 39
  },
  "IT": {
    "economicStrength": 39,
    "taxTariffFriction": 40
  },
  "KR": {
    "economicStrength": 46,
    "taxTariffFriction": 56
  },
  "SA": {
    "economicStrength": 26,
    "taxTariffFriction": 61
  },
  "SE": {
    "economicStrength": 44,
    "taxTariffFriction": 35
  },
  "PL": {
    "economicStrength": 52,
    "taxTariffFriction": 35
  },
  "ID": {
    "economicStrength": 54,
    "taxTariffFriction": 61
  }
}
